title: "Re:Mind Guide"
description: "Re:Mind guide to getting started"
theme: just-the-docs

url: https://clirdlf.github.io/remind_guide

baseurl: /remind_guide

aux_links:
  CLIR: https://www.clir.org

aux_links_new_tab: true

color_scheme: clir

logo: "/assets/images/clir-red-symbol.png"
favicon_ico: "/assets/images/favicon.ico"

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# Note: the main Just the Docs site does *not* use Google Analytics.
ga_tracking: 
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

heading_anchors: true

search_enabled: true
mermaid: 
  version: "9.1.3"

footer_content: "&copy; 2024 <a target='_blank' href='https://www.clir.org'>CLIR</a>. Distributed by an <a href=\"https://github.com/clirdlf/remind_guide/tree/main/LICENSE\">MIT license.</a>"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/clirdlf/remind_guide" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

plugins:
  - jekyll-seo-tag

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # theme test code
  - fixtures/