title: Uendelevu wa Urithi wa Utamaduni Unaozaa Katika Kipindi cha Mabadiliko ya Tabianchi
lang_name: Swahili
description: 
short_title: Re:Mind Mwongozo wa Shamba
follow_along: Fuatilia kwenye GitHub
search: Tafuta
get_started: Anza
not_available: Samahani, ukurasa huu haupatikani kwa lugha hii.
tagline: Mwongozo wa uwanja wa vitu
support: Msaada
built_by: Imetolewa na <a class="link-secondary" target="_blank" href="https://www.clir.org/">CLIR</a>. Nambari chanzo inapatikana kwenye <a class="link-secondary" target="_blank" href="https://github.com/clirdlf/remind_guide">GitHub</a>.





